config/routes.rb
Rails.application.routes.draw do


  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }


  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  scope module: 'user' do
 		get '/users/mypage', to: 'users#mypage', as: 'mypage'
 		get '/users/mypage/info', to: 'users#info', as: 'info'
 		get '/users/mypage/info_edit', to: 'users#edit', as: 'edit'
    resources :users, only: [:update] do
 		  get :confirm, on: :member # 退会確認
     patch :withdrawal, on: :member # 退会処理
 		end
 		resources :items, only: [:index, :show]
 		resources :cart_items, only: [:create, :index, :update, :destroy]
 		resources :orders, only: [:new, :create, :index, :show]
 		post '/orders/confirmation', to: 'orders#confirmation', as: 'orders_confirmation'
  	get '/orders/complete', to: 'orders#complete', as: 'orders_complete'
  	resources :genres,only: [:show, :index]
  end


  namespace :admin do
		resources :items,only: [:index, :new, :create, :show, :edit, :update, :destroy]
	  resources :users,only: [:index, :show, :edit, :update]
    resources :orders,only: [:show, :index]
    resources :orders_detail,only: [:show]
    resources :genres
	end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items
  has_many :orders

  def activate!
    update(is_active: true)
  end

  def deactivate!
    update(is_active: false)
  end
end

app/controllers/user/cart_items_controller.rb
class User::CartItemsController < ApplicationController
  before_action :set_cart_item, only: [:update,:destroy]


  def create
    item = Item.find(cart_item_params[:item_id])
    size = cart_item_params[:size]
    amount = cart_item_params[:amount].to_i
    @user_cart_item = current_user.cart_items.find_by(item_id: item.id, size: size)

    if @user_cart_item
      @user_cart_item.amount += amount
      @user_cart_item.save
    else
      @cart_item = current_user.cart_items.build(item: item, amount: amount, size: size)
      if @cart_item.save
        flash[:success] = "カートに追加しました。"
      else
        flash[:error] = "商品をカートに追加できませんでした。"
        redirect_to item_path(item) and return
      end
    end
    redirect_to cart_items_path
  end
  
  def index
    @cart_items = current_user.cart_items
    @total_amount = @cart_items.sum(&:subtotal)
    @postage = 0
    if @total_amount >= 5000
      @postage = 0
    else
      @postage = 550
    end
  end

  def update
    if @cart_item.update(cart_item_params)
      @total_amount = current_user.cart_items.sum(&:subtotal)
      respond_to do |format|
        format.html { redirect_to cart_items_path, notice: '数量が変更されました。' }
        format.json do
          render json: {
            item_id: @cart_item.id,
            item_subtotal: view_context.number_with_delimiter(@cart_item.subtotal),
            total_amount: view_context.number_with_delimiter(@total_amount)
          }
        end
      end
    else
      flash[:error] = "カートアイテムの更新に失敗しました。"
      render :index
    end
  end

  def destroy
    @cart_item.destroy
    flash[:success] = "商品をカートから削除しました。"
    redirect_to cart_items_path
  end

  private

  def set_cart_item
    @cart_item = CartItem.find(params[:id])
  end

  def cart_item_params
    params.require(:cart_item).permit(:item_id, :amount, :size)
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/genres_controller.rb
class User::GenresController < ApplicationController

  def index
    @genres = Genre.all
  end

  def show
    @genre = Genre.find(params[:id])
    @items = @genre.items
  end

  def genre_params
    params.require(:genre).permit(:name, :image)
  end

end

app/controllers/user/items_controller.rb
class User::ItemsController < ApplicationController

  def index
    @item = Item.new
    @items = Item.page(params[:page])
  end
  
  def show
    @item = Item.find(params[:id])
    @cart_item = current_user.cart_items.new if user_signed_in?
  end

  private

  def item_params
    params.require(:item).permit(:name, :introduction, :price, :color, :image, :genre_id)
  end

end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/orders_controller.rb
class User::OrdersController < ApplicationController

  def new #注文情報入力
    if current_user.cart_items.empty?
    redirect_to item_index_path, alert: "カートに商品がありません。"
    else
      @order = Order.new
      @total_amount = current_user.cart_items.sum(&:subtotal)
      @order.postage = @total_amount >= 5000 ? 0 : 550
    end
  end

  def confirmation #注文情報確認
    @cart_items = current_user.cart_items
    @order = Order.new(order_params)
    @order.user_id = current_user.id

    @total_amount = current_user.cart_items.sum(&:subtotal)
    @order.postage = @total_amount >= 5000 ? 0 : 550
    @total_payment = @total_amount + @order.postage

    @order.shipping_postal_code = current_user.postal_code
    @order.shipping_address = current_user.address
    @order.shipping_name = current_user.last_name + current_user.first_name
  end

  def create
    @order = Order.new(order_params)
    @order.user_id = current_user.id
    @total_amount = current_user.cart_items.sum(&:subtotal)
    @order.postage = @total_amount >= 5000 ? 0 : 550

    if @order.save
      @cart_items = current_user.cart_items
      @cart_items.each do |cart_item|
        order_detail = OrderDetail.new(
          order_id: @order.id, # order_idを設定
          purchase_price: cart_item.item.price,
          amount: cart_item.amount,
          size: cart_item.size,
          item_id: cart_item.item_id
        )
        order_detail.save!
      end
      @cart_items.destroy_all
      redirect_to orders_complete_path
    else
      render :new
    end
  end

  def complete #注文完了画面
  end

  def index #注文履歴画面
    @orders = current_user.orders.order(created_at: :desc)
  end

  def show # 注文履歴詳細画面
    if params[:id] == "complete"
      # 注文完了画面を表示する処理
      render "complete"
    else
      @order = Order.find(params[:id])
      @order_details = @order.order_details.all
      @total_payment = @order.calculate_total_payment
    end
  end

  private

  def order_params
    params.require(:order).permit(:user_id, :shipping_postal_code, :shipping_address, :shipping_name, :postage, :total_payment, :payment_method)
  end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    mypage_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name,:first_name,:last_name_kana,:first_name_kana,:telephone_number,:postal_code,:address])
   end
  
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :user_state, only: [:create]

  def create
    user = User.find_by(email: params[:user][:email])

    if user && user.valid_password?(params[:user][:password]) && user.is_active
      sign_in user
      redirect_to mypage_path
    else
      flash[:alert] = "ログインできません。アカウントが無効になっているか、パスワードが正しくありません。"
      render 'user/registrations/new'
    end
  end

  protected

  def user_state
    @user = User.find_by(email: params[:user][:email])

    if !@user
      flash[:alert] = "アカウントが見つかりませんでした。"
      redirect_to new_user_registration_path
    elsif !@user.is_active?
      flash[:alert] = "退会済みのアカウントです。"
      redirect_to new_user_registration_path
    end
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:mypage, :info, :edit, :update, :confirm, :withdrawal]

  def mypage #顧客のマイページ
    @user = current_user
  end

  def info #顧客の登録情報画面
    @user = current_user
  end

  def edit #顧客の登録情報編集画面
    @user = current_user
  end

  def update #顧客の登録情報更新
    @user = current_user
    if @user.update(user_params)
      flash[:notice] = '登録情報を更新しました'
      redirect_to info_path
    else
      render 'users_info_edit'
    end
  end

  def confirm #退会確認画面
    is_matching_login_user
    @user = User.find(params[:id])
  end

  def withdrawal  #退会画面
    @user = User.find(params[:id])
    @user.update(is_active: false)
    sign_out @user
    redirect_to root_path, notice: "アカウントが削除されました。"
  end

  private

  def user_params
    params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :postal_code, :address, :telephone_number, :is_active, :password, :password_confirmation)
  end

  def is_matching_login_user
    @user = current_user
    unless @user.id == current_user.id
      redirect_to mypage_path
    end
  end

end

app/helpers/user/genres_helper.rb
module User::GenresHelper
end

app/helpers/user/items_helper.rb
module User::ItemsHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/user/users/confirm.html.erb
<div class="container">
  <h5 style="text-align: center;">
    <b>退会</b>
  </h5>

  <div class="row justify-content-center">
    <div class="col-md-10">
      <p>下記の注意事項を確認のうえ、チェックを入れて「退会する」ボタンを押してください</p>

      <div class="withdraw-checked">
        <label>
          <input type="checkbox" name="withdraw_agreement" id="withdraw-agreement">
          退会後、登録内容はできなくなります
        </label>
      </div>

      <div class="withdraw-checked">
        <label>
          <input type="checkbox" name="withdraw_agreement" id="withdraw-agreement">
          既にご注文いただいている商品は、退会後も発送させていただきます
        </label>
      </div>

      <div class="row justify-content-center">
        <div class="col-md-6">
          <%= form_with(model: @user, url: withdrawal_user_path(@user), method: :patch, id: 'withdraw-button') do |f| %>
            <%= f.submit "退会する", class: "btn btn-outline-danger btn-block" %>
          <% end %>
        </div>
      </div>

      <div class="row justify-content-center">
        <div class="col-md-6">
          <%= link_to "戻る", mypage_path , class: "btn btn-light btn-block" %>
        </div>
      </div>

    </div>
  </div>

</div>

app/views/user/users/edit.html.erb
<div class="container">
<h5 style="text-align: center;"><b>会員情報変更</b></h5>

  <div class="row justify-content-center">
    <div class="col-md-6">

    <%= form_for @user, url: user_path(@user), method: :patch do |f| %>

      <!-- エラーチェック -->
      <% if @user.errors.any? %>
        <%= @user.errors.count %> errors prohibited this obj from being saved:
        <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      <% end %>

      <div class="row form-group">
        <div class="col-md-12">
          <b><%= f.label :'名前（必須)' %></b>
        </div>
        <%= f.text_field :last_name, placeholder: '(例)山田',autofocus: true, class: "col-md-6 example-text" %>
        <%= f.text_field :first_name, placeholder: '(例)太郎',autofocus: true, class: "col-md-6 example-text" %>
      </div>

      <div class="row form-group">
        <div class="col-md-12">
          <b><%= f.label :'カナ（必須）' %></b>
        </div>
        <%= f.text_field :last_name_kana, placeholder: '(例)ヤマダ', autofocus: true, class: "col-md-6" %>
        <%= f.text_field :first_name_kana, placeholder: '(例)タロウ', autofocus: true, class: "col-md-6" %>
      </div>

      <div class="row form-group">
        <b><%= f.label :"郵便番号(ハイフンなし)", class: "col-md-12" %></b>
        <%= f.text_field :postal_code, placeholder: '0123456', autofocus: true, class: "col-md-12" %>
      </div>

      <div class="row form-group">
        <b><%= f.label :住所, class: "col-md-12" %></b>
        <%= f.text_field :address, placeholder: '○○県△△市××町1-2-3' , autofocus: true, class: "col-md-12" %>
      </div>

      <div class="row form-group">
        <b><%= f.label :"電話番号(ハイフンなし)", class: "col-md-12" %></b>
        <%= f.text_field :telephone_number, placeholder: '0123456789', autofocus: true, class: "col-md-12" %>
      </div>

      <div class="row form-group">
        <b><%= f.label :メールアドレス, class: "col-md-12" %></b>
        <%= f.email_field :email, placeholder: 'メールアドレスを入力してください。', autofocus: true, class: "col-md-12" %>
        <p style="color: red;">ログインの際に必要になります。忘れないようにしてください。</p>
      </div>

      <div class="row justify-content-center">
        <div class="col-md-6">
          <%= f.submit "変更する" ,class: "btn btn-dark btn-block" %>
        </div>
      </div>
      
      <div class="row justify-content-center">
        <div class="col-md-6">
          <%= link_to "戻る", mypage_path , class: "btn btn-light btn-block" %>
        </div>
      </div>

    <% end %>
    </div>
  </div>
</div>

app/views/user/users/info.html.erb
<div class="container">
<h5 style="text-align: center;">
  <b>会員登録情報</b>
  <%= link_to edit_path do %>
    <i class="fa-solid fa-user-pen"></i>
  <% end %>
</h5>


  <div class="row justify-content-center">
    <div class="col-md-6">
      <% if @user.present? %>
        <div class="row form-group">
          <div class="col-md-12">
            <b>氏名</b>
          </div>
          <%= @user.last_name %>　<%= @user.first_name %>
        </div>

        <div class="row form-group">
          <div class="col-md-12">
            <b>カナ</b>
          </div>
          <%= @user.last_name_kana %>　<%= @user.first_name_kana %></td>
        </div>

        <div class="row form-group">
          <div class="col-md-12">
            <b>郵便番号</b>
          </div>
          〒<%= @user.postal_code %>
        </div>

        <div class="row form-group">
          <div class="col-md-12">
            <b>住所</b>
          </div>
          <%= @user.address %>
        </div>

        <div class="row form-group">
          <div class="col-md-12">
            <b>電話番号</b>
          </div>
          <%= @user.telephone_number %>
        </div>

        <div class="row form-group">
          <div class="col-md-12">
            <b>メールアドレス</b>
          </div>
          <%= @user.email %>
        </div>

        <div class="row justify-content-center">
          <div class="col-md-6">
            <%= link_to "戻る", mypage_path , class: "btn btn-light btn-block" %>
          </div>
        </div>


      <% end %>

    </div>
  </div>
</div>

app/views/user/users/mypage.html.erb
<div class="container">
  <h5 style="text-align: center;">
    <b>マイページ</b>
  </h5>


  <div class="row justify-content-center">
    <div class="col-md-6">
      <ul>

        <li>
          <%= link_to info_path do %>
            会員登録情報の変更
          <% end %>
        </li>

        <li class="nav-item">
          <%= button_to destroy_user_session_path, method: :delete, class: 'logout-link' do %>
            ログアウト
          <% end %>
        </li>

        <li>
          <%= link_to confirm_user_path(@user) do %>
            退会手続き
          <% end %>
        </li>

        <li>

          <%= link_to orders_path do %>
            注文履歴一覧
          <% end %>


        </li>

      </ul>
    </div>
  </div>
</div>